language: rust

sudo: false

cache: cargo

os:
- linux
- osx

rust:
- stable
- nightly

env:
- FEATURES="clippy"
- FEATURES=""

matrix:
  fast_finish: true
  exclude:
    - rust: stable
      env: FEATURES="clippy"
    - rust: nightly
      env: FEATURES=""
  allow_failures:
  - rust: nightly

script:
  - cargo test --no-default-features --features "$FEATURES"

before_deploy:
- mkdir ./target/deploy/
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    make dmg;
    TAG=${TRAVIS_TAG:-nightly};
    mv ./target/release/osx/Alacritty.dmg ./target/deploy/Alacritty_${TAG}.dmg;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    cargo build --release;
    cargo install cargo-deb;
    DEB=$( cargo deb --no-build );
    ARCH=$( uname -m );
    TAG=${TRAVIS_TAG:-nightly};
    mv $DEB ./target/deploy/alacritty_${TAG}_${ARCH}.deb;
    mv ./target/release/alacritty ./target/deploy/alacritty_${TAG}_${ARCH};
  fi
- ls ./target/deploy/;

deploy:
  provider: releases
  api_key:
    secure: o2Q39A2JAKeMEYD0dFJTpYJMpAsHYcUa4DIXApqn/ygXQzcfPpnLelCWb70zOlICIk3ICETlzeLfF7s/q802jy5aEFLbbmIp+rT0SWlRiShuQqLPkwlK7Cqh2nUAVPoozYn1y9ha8kozOL3xgDxI9RGHMC+7ZV9duVLWUqz5Ah7qBoOx9QemDMrdPJ7zi8vFvJp4oW3EV7wQRRfEmFkqOAxbAWhLeTNGVR9ECjUZIgXWRz1kjqVz6dJrLauH/D068RSV/7JM1dlzrMkBsmRe8xVOTnAiHIoGMB4UaUTLz8hJNH+KUmXfprfBKuFEQ7jDnYq+6/y200VYuRfRsU2EOqYjzHXmWD6E3vkHhVdrUUfFmG9tfAzIXFZxs0LVIszWgqqMypmuLNxgYcfpMmo+YeHGWX59HOVwXmvY38ix1++zLh44kpRuX0mYFuPdH6gRdeKPr7jyueODKRwsegh1d8rVl7T0HQpBmDcWHBidOf8Aw8NTrsEoRQFlS/eVZyGnZet/nf6Otenp/5MIBA3BHO9R9QaCo0FT3Yi7FL/kkoEZs+lN5mKJulZ6hpmG760h+mYBqw7buLKcCR3qBiuXOpgfzNWgOoAGb3G7eUAhCf1zHTEcdL6U/SEA2ofpaPZGqrcuZ7aTgnJ6lWU4YWI8X+hAouv6IOk/UoxiONIUwHE=
  skip_cleanup: true
  file_glob: true
  file: "target/deploy/*"
  on:
    rust: stable
    all_branches: true
    condition: '$TRAVIS_TAG != "" || $TRAVIS_EVENT_TYPE = "cron"'
